spring:
  config:
    activate:
      on-profile: test

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=false;MODE=PostgreSQL
    username: sa
    password: ""
    
websocket:
  user-destination-prefix: dummy_value
  allow-origin: dummy_value
  application-prefix: dummy_value
  destination-prefix: dummy_value
rabbitmq:
  exchanges:
    bid-exchange: dummy_value
  routing-keys:
    notification: dummy_value
  exchanges:
    notification-exchange: dummy_value
  queues:
    notification-queue: dummy_value
openapi:
  service:
    api-docs: dummy_value
websocket:
  endpoint: dummy_value

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: reuse-hub-api-docs
    server: ${BACKEND_SERVICE:http://localhost:${server.port}}
    title: reuse-hub
    version: 1.0.0
