spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:postgresql://localhost:5432/auction
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        spatial:
          dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect

    
websocket:
  allow-origin: dummy_value
  application-prefix: dummy_value
  destination-prefix: dummy_value
  endpoint: /ws

rabbitmq:
  exchanges:
    bid-exchange: dummy_value
    notification-exchange: dummy_value
  routing-keys:
    notification: dummy_value
  queues:
    notification-queue: dummy_value
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: reuse-hub-api-docs
    server: ${BACKEND_SERVICE:http://localhost:${server.port}}
    title: reuse-hub
    version: 1.0.0
