apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
  namespace: reuse-hub
  labels:
    app: item-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-service
  template:
    metadata:
      labels:
        app: item-service
    spec:
      containers:
        - name: item-service
          image: reuse-hub/item-service:latest
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: reuse-hub-config
            - secretRef:
                name: reuse-hub-secret
          env:
            - name: DATABASE_URL_ITEM
              valueFrom:
                configMapKeyRef:
                  name: reuse-hub-config
                  key: DATABASE_URL_ITEM
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: reuse-hub-config
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reuse-hub-secret
                  key: DATABASE_PASSWORD
            - name: BACKEND_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: reuse-hub-config
                  key: BACKEND_SERVICE_ITEM
          resources:
            limits:
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: item-service
  namespace: reuse-hub
spec:
  selector:
    app: item-service
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
