spring:
  config:
    activate:
      on-profile: test
rabbitmq:
  exchange:
    item: ex.item
    transaction: ex.transaction
  routing-key:
    item:
      viewed: r.item.viewed
      liked: r.item.liked
    transaction:
      completed: r.transaction.completed
  queue:
    recommendation:
      events: q.recommendation.events

neo4j:
  uri: bolt://localhost:7687
  authentication:
    username: neo4j
    password: 12345678

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: reuse-hub-api-docs
    server: ${BACKEND_SERVICE:http://localhost:${server.port}}
    title: reuse-hub
    version: 1.0.0