spring:
  config:
    activate:
      on-profile: test

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

rabbitmq:
  queue:
    ai-scan: q.saga.ai-scan.test

google:
  ai:
    api-key: "test-api-key"
    model: "test-model"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: reuse-hub-api-docs
    server: ${BACKEND_SERVICE:http://localhost:${server.port}}
    title: reuse-hub
    version: 1.0.0