server:
  port: 8083
  servlet:
    context-path: "/api/v1/items"
spring:
  application:
    name: item-service
  profiles:
    active: @spring.profiles.active@

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO